#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Nov 12 18:57:09 2017

@author: frouglas
"""

import xml.etree.ElementTree as ET

def getPredictions(resultText):
    response = ET.fromstring(resultText)
    response[0][0].text
    breakPt = 1
    return 1
        